# Generated by Django 2.0.1 on 2018-01-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='situation_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='situation',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
